version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: codive-ai-server
    expose:
      - "8000"  # 외부 노출 X, 같은 네트워크인 Nginx에게만 노출
    restart: always

  nginx:
    image: nginx:latest
    container_name: codive-nginx
    ports:
      - "80:80" # 외부(사용자)는 80포트로 접속
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
    restart: always